### DISCUSSION TITLE
[Frontend] Changesets Version 후, 자동으로 Github Release 기능 추가

### DISCUSSION THREAD

**Discussion by rkskekzzz** [80000Coding/80000Coding-Web-Client#82] [General]
## 추가할 기능
현재 changeset action or cli로 version을 업데이트 하는 경우, github release가 자동으로 생성되지 않습니다. 추후 아래 방법 중, 한가지를 선택해서 자동으로 release가 생성될 수 있도록 작업해야 합니다.

1. npm package 배포 후, action을 아래와 같이 수정 ( yarn 은 npm 명령으로 수정 필요)
```yml
   - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
2. github release action을 별도로 추가 [참고링크](https://github.com/actions/create-release)
